# Generated by Django 5.0.1 on 2024-06-18 15:52

import django.db.models.deletion
import propylon_document_manager.castorage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="path",
            field=models.CharField(db_index=True, default="/", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fileversion",
            name="uploaded_file",
            field=models.FileField(
                null=True,
                upload_to="files",
                verbose_name=propylon_document_manager.castorage.CAStorage(location="files"),
            ),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
