# Generated by Django 5.0.1 on 2024-06-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileversion_archived_fileversion_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="content_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
